import { useEffect, useMemo, useState } from 'react';
import './App.css';
import { DefaultDownloadDirectory, GetDownloadStatuses, SelectOutputDirectory, SelectTorrent, SetOutputDirectory, StartTorrent, StopTorrent } from '../wailsjs/go/main/App';

type Status = { state: string; name: string; torrentPath: string; outputDir: string; totalBytes: number; downloadedBytes: number; pieceCount: number; completedPieces: number; peerCount: number; port: number; error: string };
const empty: Status = { state: 'queued', name: '', torrentPath: '', outputDir: '', totalBytes: 0, downloadedBytes: 0, pieceCount: 0, completedPieces: 0, peerCount: 0, port: 0, error: '' };

function Icon({ name, size = 16 }: { name: string; size?: number }) {
    const paths: Record<string, string> = { plus: 'M12 5v14M5 12h14', search: 'm21 21-4.3-4.3M10.8 18a7.2 7.2 0 1 1 0-14.4 7.2 7.2 0 0 1 0 14.4Z', download: 'M12 3v12m0 0 4-4m-4 4-4-4M4 20h16', pause: 'M9 5v14M15 5v14', play: 'm9 5 10 7-10 7V5Z', trash: 'M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3', settings: 'M12 15.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-1.8 1.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-2.6V20a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1-1.8-1.8.1-.1A1.7 1.7 0 0 0 8 15a1.7 1.7 0 0 0-1.6-1H6v-2.6h.2A1.7 1.7 0 0 0 8 10a1.7 1.7 0 0 0-.3-1.9l-.1-.1 1.8-1.8.1.1a1.7 1.7 0 0 0 1.9.3 1.7 1.7 0 0 0 1-1.6v-.2H15V5a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1 1.8 1.8-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2V14H21a1.7 1.7 0 0 0-1.6 1Z', folder: 'M3.5 7.5A1.5 1.5 0 0 1 5 6h4l2 2h8A1.5 1.5 0 0 1 20.5 9.5v8A1.5 1.5 0 0 1 19 19H5a1.5 1.5 0 0 1-1.5-1.5v-10Z', file: 'M6 3.5h7l5 5v12H6a2 2 0 0 1-2-2v-13a2 2 0 0 1 2-2Zm7 0v5h5M8 13h8M8 16h5', globe: 'M12 21a9 9 0 1 0 0-18 9 9 0 0 0 0 18Zm-8.5-9h17M12 3c2.2 2.4 3.3 5.4 3.3 9s-1.1 6.6-3.3 9c-2.2-2.4-3.3-5.4-3.3-9S9.8 5.4 12 3Z', check: 'm5 12 4 4L19 6', close: 'M6 6l12 12M18 6 6 18', chevronDown: 'm7 10 5 5 5-5', info: 'M12 16v-4M12 8h.01M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z', arrows: 'M7 7h10l-3-3m3 13H7l3 3', bolt: 'm13 2-8 11h6l-1 9 8-11h-6l1-9Z', cloud: 'M7 18h10a4 4 0 0 0 .6-8A6 6 0 0 0 6 11a3.5 3.5 0 0 0 1 7Z' };
    return <svg className="icon" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name] || paths.info} /></svg>;
}
function bytes(value: number) { if (!value) return '—'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const n = Math.min(Math.floor(Math.log(value) / Math.log(1024)), 4); return `${(value / 1024 ** n).toFixed(n ? 1 : 0)} ${units[n]}`; }
function nameOf(path: string) { return path ? path.split(/[\\/]/).pop() || path : 'Untitled torrent'; }
function isActive(state: string) { return ['starting', 'discovering', 'connecting', 'negotiating', 'downloading', 'stopping'].includes(state); }
function stateLabel(state: string) { if (state === 'discovering') return 'Finding peers'; if (state === 'connecting') return 'Connecting'; if (state === 'negotiating') return 'Negotiating'; if (state === 'stopping') return 'Stopping'; if (state === 'error') return 'Error'; if (state === 'complete') return 'Completed'; if (state === 'downloading') return 'Downloading'; return 'Queued'; }

function App() {
    const [library, setLibrary] = useState<Status[]>([]); const [selectedPath, setSelectedPath] = useState(''); const [output, setOutput] = useState(''); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('all'); const [settingsOpen, setSettingsOpen] = useState(false); const [details, setDetails] = useState(true); const [error, setError] = useState('');
    useEffect(() => { DefaultDownloadDirectory().then(setOutput).catch(() => undefined); const refresh = () => GetDownloadStatuses().then(remote => setLibrary(current => current.map(item => remote.find(row => row.torrentPath === item.torrentPath) || item))).catch(() => undefined); refresh(); const timer = window.setInterval(refresh, 1000); return () => window.clearInterval(timer); }, []);
    const rows = useMemo(() => library.filter(row => { const textMatch = !query || row.name.toLowerCase().includes(query.toLowerCase()) || row.torrentPath.toLowerCase().includes(query.toLowerCase()); const filterMatch = filter === 'all' || (filter === 'active' && isActive(row.state)) || (filter === 'completed' && row.state === 'complete') || (filter === 'paused' && row.state === 'paused') || (filter === 'downloading' && row.state === 'downloading') || (filter === 'seeding' && row.state === 'complete'); return textMatch && filterMatch; }), [library, query, filter]);
    const selected = library.find(row => row.torrentPath === selectedPath) || rows[0]; const active = selected && isActive(selected.state); const progress = selected?.totalBytes ? Math.min(100, Math.round(selected.downloadedBytes / selected.totalBytes * 100)) : 0; const activeCount = library.filter(row => isActive(row.state)).length;
    async function addTorrent() { try { const path = await SelectTorrent(); if (!path) return; if (library.some(row => row.torrentPath === path)) { setSelectedPath(path); return; } const row = { ...empty, name: nameOf(path), torrentPath: path, outputDir: output }; setLibrary(current => [...current, row]); setSelectedPath(path); setError(''); } catch (e) { setError(String(e)); } }
    async function chooseOutput() { try { const path = await SelectOutputDirectory(); if (path) { setOutput(path); await SetOutputDirectory(path); setLibrary(current => current.map(row => row.torrentPath === selectedPath && row.state === 'queued' ? { ...row, outputDir: path } : row)); } } catch { setError('The folder dialog could not open. Enter the path in Settings.'); } }
    async function startSelected() { if (!selected) return; const destination = selected.outputDir || output; if (!destination) { setError('Choose a download location in Settings first.'); setSettingsOpen(true); return; } try { setError(''); await StartTorrent(selected.torrentPath, destination); } catch (e) { setError(String(e)); } }
    async function stopSelected() { if (selected) await StopTorrent(selected.torrentPath); }
    return <main className="desktop-shell">
        <aside className="nav-rail"><div className="app-brand"><span className="brand-glyph">C</span><span>Cantaloupe</span></div><button className="add-button" onClick={addTorrent}><Icon name="plus" /> Add torrent</button><nav className="nav-groups"><div className="nav-caption">LIBRARY</div><button className={`nav-link ${filter === 'all' ? 'selected' : ''}`} onClick={() => setFilter('all')}><Icon name="download" /> All torrents <b>{library.length}</b></button><button className={`nav-link ${filter === 'active' ? 'selected' : ''}`} onClick={() => setFilter('active')}><Icon name="play" /> Active <b>{activeCount}</b></button><button className={`nav-link ${filter === 'completed' ? 'selected' : ''}`} onClick={() => setFilter('completed')}><Icon name="check" /> Completed</button><button className={`nav-link ${filter === 'paused' ? 'selected' : ''}`} onClick={() => setFilter('paused')}><Icon name="pause" /> Paused</button><div className="nav-caption second">FILTERS</div><button className={`nav-link ${filter === 'downloading' ? 'selected' : ''}`} onClick={() => setFilter('downloading')}><span className="filter-dot lime" />Downloading</button><button className={`nav-link ${filter === 'seeding' ? 'selected' : ''}`} onClick={() => setFilter('seeding')}><span className="filter-dot blue" />Seeding</button></nav><div className="nav-bottom"><button className="nav-link" onClick={() => setSettingsOpen(true)}><Icon name="settings" /> Settings</button><div className="engine-status"><span className="status-light" /><div><strong>Engine online</strong><small>Port {selected?.port || '—'}</small></div></div></div></aside>
        <section className="main-pane"><header className="window-bar"><div><span className="eyebrow">TORRENTS</span><h1>All torrents</h1></div><div className="window-actions"><button className="icon-button" title="Settings" onClick={() => setSettingsOpen(true)}><Icon name="settings" /></button><button className="profile">M</button></div></header>
            <div className="toolbar"><div className="toolbar-left"><button className="tool primary-tool" onClick={addTorrent}><Icon name="plus" /> Add torrent</button><button className="tool" onClick={startSelected} disabled={!selected || active}><Icon name="play" /> Start</button><button className="tool" onClick={stopSelected} disabled={!active}><Icon name="pause" /> Pause</button><span className="tool-separator" /><button className="tool" disabled={!selected}><Icon name="trash" /> Remove</button></div><label className="search"><Icon name="search" /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Filter torrents" /></label></div>
            {error && <div className="ui-error"><Icon name="info" /><span>{error}</span><button onClick={() => setError('')}><Icon name="close" size={13} /></button></div>}
            <div className="table-wrap"><div className="table-head"><span className="name-col">NAME</span><span>STATUS</span><span>PROGRESS</span><span>DOWNLOAD</span><span>UPLOAD</span><span>PEERS</span><span>SIZE</span></div>{rows.length ? rows.map(row => { const percent = row.totalBytes ? Math.round(row.downloadedBytes / row.totalBytes * 100) : 0; const running = isActive(row.state); return <div className={`torrent-row ${selected?.torrentPath === row.torrentPath ? 'row-selected' : ''}`} key={row.torrentPath} onClick={() => { setSelectedPath(row.torrentPath); setDetails(true); }}><div className="name-col torrent-title"><span className="torrent-icon"><Icon name="file" /></span><div><strong>{row.name || nameOf(row.torrentPath)}</strong><small>{row.outputDir ? nameOf(row.outputDir) : 'No location selected'}</small></div></div><span><i className={`state-dot ${row.state === 'complete' ? 'done' : ''}`} />{stateLabel(row.state)}</span><div className="row-progress"><div className="mini-track"><i style={{ width: `${percent}%` }} /></div><small>{percent}%</small></div><span className="rate">—</span><span className="rate">—</span><span className="peer-count">{row.peerCount || '—'}</span><span>{bytes(row.totalBytes)}</span></div>; }) : <div className="table-empty"><div className="empty-symbol"><Icon name={query ? 'search' : 'cloud'} size={23} /></div><strong>{query ? 'No matching torrents' : 'No torrents added'}</strong><span>{query ? 'Try a different filter.' : 'Add a torrent file to begin downloading.'}</span><button className="empty-action" onClick={addTorrent}><Icon name="plus" /> Add torrent</button></div>}</div>
            <div className="details-pane"><div className="details-tabs"><button className="tab active-tab">Overview</button><button className="tab">Files</button><button className="tab">Peers</button><button className="tab">Trackers</button><button className="collapse" onClick={() => setDetails(!details)}><Icon name={details ? 'chevronDown' : 'info'} /></button></div>{details && <div className="details-content">{selected ? <><div className="detail-title"><span className="torrent-icon large"><Icon name="file" size={19} /></span><div><strong>{selected.name || nameOf(selected.torrentPath)}</strong><small>{selected.state === 'complete' ? 'Download complete' : active ? stateLabel(selected.state) : 'Ready to download'}</small></div></div><div className="detail-grid"><div><label>PROGRESS</label><strong>{progress}% <small>{bytes(selected.downloadedBytes)} / {bytes(selected.totalBytes)}</small></strong></div><div><label>PIECES VERIFIED</label><strong>{selected.completedPieces} <small>/ {selected.pieceCount}</small></strong></div><div><label>PEERS</label><strong>{selected.peerCount || '—'}</strong></div><div><label>DOWNLOAD TO</label><strong className="path-value"><Icon name="folder" size={13} /> {selected.outputDir || output || 'No location selected'}</strong></div></div>{selected.error && <div className="inline-error"><Icon name="info" /> {selected.error}</div>}</> : <div className="details-placeholder"><Icon name="info" /><span>Select a torrent to view its details</span></div>}</div>}</div>
            <footer className="status-bar"><span><i className="status-light" /> Engine online</span><span><Icon name="arrows" size={13} /> Down — &nbsp; Up —</span><span className="secure"><Icon name="bolt" size={12} /> SHA-1 verification on</span></footer>
        </section>
        {settingsOpen && <div className="modal-backdrop" onClick={() => setSettingsOpen(false)}><section className="settings-modal" onClick={event => event.stopPropagation()}><div className="modal-head"><div><h2>Settings</h2><p>Download and connection preferences</p></div><button className="close-button" onClick={() => setSettingsOpen(false)}><Icon name="close" /></button></div><div className="settings-section"><label>Default download location</label><div className="setting-path"><input value={output} onChange={event => { setOutput(event.target.value); SetOutputDirectory(event.target.value); }} placeholder="C:\Users\You\Downloads" /><button onClick={chooseOutput}>Browse…</button></div><small>This location is used for newly added torrents.</small></div><div className="settings-section"><label>Connection</label><div className="setting-row"><div><strong>Listening port</strong><small>Assigned automatically by the engine</small></div><span>{selected?.port || '—'}</span></div><div className="setting-row"><div><strong>Verify pieces before saving</strong><small>Checks each block against the torrent hash</small></div><span className="toggle on"><i /></span></div></div><div className="modal-foot"><span>Changes are saved automatically</span><button className="done-button" onClick={() => setSettingsOpen(false)}>Done</button></div></section></div>}
    </main>;
}
export default App;
