// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DefaultDownloadDirectory() {
  return window['go']['main']['App']['DefaultDownloadDirectory']();
}

export function GetDownloadStatus() {
  return window['go']['main']['App']['GetDownloadStatus']();
}

export function GetDownloadStatuses() {
  return window['go']['main']['App']['GetDownloadStatuses']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function SelectOutputDirectory() {
  return window['go']['main']['App']['SelectOutputDirectory']();
}

export function SelectTorrent() {
  return window['go']['main']['App']['SelectTorrent']();
}

export function SetOutputDirectory(arg1) {
  return window['go']['main']['App']['SetOutputDirectory'](arg1);
}

export function SetTorrentPath(arg1) {
  return window['go']['main']['App']['SetTorrentPath'](arg1);
}

export function StartDownload() {
  return window['go']['main']['App']['StartDownload']();
}

export function StartTorrent(arg1, arg2) {
  return window['go']['main']['App']['StartTorrent'](arg1, arg2);
}

export function StopDownload() {
  return window['go']['main']['App']['StopDownload']();
}

export function StopTorrent(arg1) {
  return window['go']['main']['App']['StopTorrent'](arg1);
}
