// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DefaultDownloadDirectory():Promise<string>;

export function GetDownloadStatus():Promise<main.DownloadStatus>;

export function GetDownloadStatuses():Promise<Array<main.DownloadStatus>>;

export function GetTorrentFiles(arg1:string):Promise<Array<main.TorrentFile>>;

export function GetTorrentPeers(arg1:string):Promise<Array<main.TorrentPeer>>;

export function GetTorrentTrackers(arg1:string):Promise<Array<main.TorrentTracker>>;

export function GetVerifyPieces():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;

export function RemoveTorrent(arg1:string):Promise<void>;

export function SelectOutputDirectory():Promise<string>;

export function SelectTorrent():Promise<string>;

export function SetOutputDirectory(arg1:string):Promise<void>;

export function SetTorrentPath(arg1:string):Promise<void>;

export function SetVerifyPieces(arg1:boolean):Promise<void>;

export function StartDownload():Promise<void>;

export function StartTorrent(arg1:string,arg2:string):Promise<void>;

export function StopDownload():Promise<void>;

export function StopTorrent(arg1:string):Promise<void>;
